apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: rails-pipelinerun
spec:
  pipelineRef:
    name: rails-pipeline
  params:
    - name: IMAGE
      value: sanoobshan/rails-app:latest
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: shared-workspace-claim
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: dockerconfig
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json