apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: rails-pipelinerun-
spec:
  pipelineRef:
    name: rails-pipeline
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
