apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rails-pipeline
spec:
  params:
    - name: IMAGE
      type: string
      description: The image to build and push
  workspaces:
    - name: shared-workspace

  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "https://github.com/sanoobshan/rails-app.git"
        - name: revision
          value: "main"

    - name: build-and-push
      taskRef:
        name: kaniko
        kind: ClusterTask
      runAfter:
        - fetch-source
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: sanoobshan/rails-app:latest
